### ISSUE TITLE
Add An existing Template

### ISSUE THREAD

**Issue by codeAtNight009** [codeAtNight009/DevgenicsPortfolioSite#1]
Add an existing Template on the top of which we can make Devgenics Portfolio Site.

**Comment by himalaya2Point0** [comment]
Devgenics is a digital agency so the template should be like that only
Template should be very interactive too.

**Comment by himalaya0035** [comment]
Please assign this issue to me. I can find such templates Easily

**Comment by codeAtNight009** [comment]
Ok , I am assigning it to you, but please make sure you follow the description.
Attach Images of your template in the pr

**Comment by himalaya0035** [comment]
Ok I will do the same

**Comment by codeAtNight009** [comment]
Assigned !
