### ISSUE TITLE
Rename , remove and so on....

### ISSUE THREAD

**Issue by codeAtNight009** [codeAtNight009/DevgenicsPortfolioSite#3]
Hi contributors, 
I have some beginner friendly task for you.
For a Valid Pr, do the following : 
1) Change the name of the site To 'Devgenics'
2) Remove portfolio option from the navbar
See this image
![image](https://user-images.githubusercontent.com/91694012/135768440-cf237527-f474-42f0-93ea-be1ce25e9f34.png)

3) Remove this section given in the image below
![image](https://user-images.githubusercontent.com/91694012/135768468-642d454e-538e-4e6f-b129-bf2a497aa35e.png)

Follow all the task for a valid Pr

**Comment by shiv0403** [comment]
Please assign this issue to me @codeAtNight009

**Comment by AkhilChoubey** [comment]
I can work on this issue , if assigned..
