### ISSUE TITLE
write content ....

### ISSUE THREAD

**Issue by codeAtNight009** [codeAtNight009/DevgenicsPortfolioSite#5]
Hi contributors, 
I am creating this issue to help you complete 4 prs.

For a valid pr, do the following 
1) In this image leave the heading as it is, but change the text below that so it matches the heading.
![image](https://user-images.githubusercontent.com/91694012/135808091-6bd654aa-2e52-4c06-868b-6d4511a0e314.png)

Ex : The first heading says : Reach Out, so the text below could be like this "React out to us to get a free consultation for your site."
Develop A strategy  --> "Together we develop a sustainable strategy that we all think will be best for your site"

These are 2 rough samples I have given you, be more creative.

2) Replace the text "Features" with "Workflow"
![image](https://user-images.githubusercontent.com/91694012/135808534-b9508e28-fb3f-46b7-a3a3-992c4dee8a6d.png)

Hope you understood the tasks well.

I will at max assign 3 people to do the task, the one who does the best will get his pr Merged.
Support your Pr/Images with images, otherwise I would not be able to accept them.

**Comment by anishsaraogi** [comment]
I would like to work on this issue, please assign it to me.

**Comment by codeAtNight009** [comment]
Ok bro, assigned

**Comment by sankitanitdgp** [comment]
can u assign it to me also, please

**Comment by codeAtNight009** [comment]
Yes Sankita, Assigned !

**Comment by anishsaraogi** [comment]
I have fixed the issue and created a pull request

**Comment by sankitanitdgp** [comment]
Hey @codeAtNight009 , I've resolved the 2nd issue and raised a PR

**Comment by anishsaraogi** [comment]
@codeAtNight009 please close the issue as it's resolved
