### ISSUE TITLE
Make Form Look Better

### ISSUE THREAD

**Issue by codeAtNight009** [codeAtNight009/DevgenicsPortfolioSite#6]
Hi contributors, 
I am creating this issue to help you complete 4 prs.

For a valid pr, do the following 
1) The contrast is really bad, make this form look better, appealing.
2) Remove this gap that I have marked in the image, make both the boxes of equal height.
![image](https://user-images.githubusercontent.com/91694012/135809473-19adfef3-9e86-49bc-99ca-7050a160c9a6.png)

Hope you understood the tasks well.

I will at max assign 3 people to do the task, the one who does the best will get his pr Merged.
Support your Pr/Images with images, otherwise I would not be able to accept them.

**Comment by shiv0403** [comment]
can you assign this issue to me @codeAtNight009 ?

**Comment by codeAtNight009** [comment]
Yes I can, Assigned !

**Comment by anishsaraogi** [comment]
I can work on this issue, please assign it to me

**Comment by codeAtNight009** [comment]
Assigned !

**Comment by anishsaraogi** [comment]
Fixed the issue and created a PR

**Comment by codeAtNight009** [comment]
I accepted it this times, but it would be better if please you support your Pr with images. It helps me to review the Pr.

**Comment by anishsaraogi** [comment]
I will make sure I do that next time!
